services:
  fuelltreffer:
    build: .
    ports:
      - "${FRONTEND_PORT:-4000}:4000"
      - "${BACKEND_PORT:-4001}:4001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3